/*
 * This source file was generated by the Gradle 'init' task
 */
package pursuit;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertTrue;

class MainTest {
    @Test
    void test() {
        assertTrue(true);
    }
}
